### ISSUE TITLE
Invalid URL: file path occasionally converted to URL

### ISSUE THREAD

**Issue by hacker-h** [tasmota/decode-config#35]
**Describe the bug**
Occasionally the absolute file path passed to decode-config is converted to a URL.
`/tmp/tasmota01.local.dmp` => `http:///tmp/tasmota01.local.dmp/dl`

**To Reproduce**
_Steps to reproduce the behavior:_
Run decode-config many times on a file, e.g.:
```
decode-config -s /tmp/tasmota01.local.dmp
```
\> 95% of the time this works fine
however occasionally it yields this error:
```
Traceback (most recent call last):
File "/usr/local/bin/decode-config", line 5207, in <module>
  CONFIG['encode'] = pull_tasmotaconfig(ARGS.device, ARGS.port, username=ARGS.username, password=ARGS.password)
File "/usr/local/bin/decode-config", line 3198, in pull_tasmotaconfig
  _, body = get_tasmotaconfig('dl', host, port, username, password, contenttype='application/octet-stream')
File "/usr/local/bin/decode-config", line 3133, in get_tasmotaconfig
  res = requests.get(url, auth=auth)
File "/home/backuper/.local/lib/python3.9/site-packages/requests/api.py", line 75, in get
  return request('get', url, params=params, **kwargs)
File "/home/backuper/.local/lib/python3.9/site-packages/requests/api.py", line 61, in request
  return session.request(method=method, url=url, **kwargs)
File "/home/backuper/.local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
  prep = self.prepare_request(req)
File "/home/backuper/.local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
  p.prepare(
File "/home/backuper/.local/lib/python3.9/site-packages/requests/models.py", line 316, in prepare
  self.prepare_url(url, params)
File "/home/backuper/.local/lib/python3.9/site-packages/requests/models.py", line 393, in prepare_url
  raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'http:///tmp/tasmota01.local.dmp/dl': No host supplied
```

**Expected behavior**
decode-config should behave always the same

**Version Information (please complete the following information):**
```bash
$ /usr/local/bin/decode-config -VV
decode-config v9.5.0 [af097d6] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config
Python:   3.9.5
Platform: Linux-5.11.0-37-generic-x86_64-with - x86_64
OS:       Linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021
Time:     2021-10-08 19:11:46
```

- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```json
{
  "bootcount": 691,
  "bootcount_reset_time": 1593870950,
  "cfg_crc": "0x36c3",
  "cfg_crc32": "0xe496b08b",
  "cfg_holder": 4617,
  "cfg_size": 4096,
  "cfg_timestamp": 1633647601,
  "header": {
    "data": {
      "crc": "0x7c2b",
      "crc32": "0xe496b08b",
      "platform": "ESP82xx",
      "size": 4096,
      "template": {
        "crc": "0x36c3",
        "crc32": "0xe496b08b",
        "size": 4096,
        "version": "0x8030100"
      },
      "version": "0x8030100"
    },
    "env": {
      "platform": "Linux-5.11.0-37-generic-x86_64-with-Ubuntu-20.04-focal",
      "python": "3.6.9",
      "script": "decode-config.py v9.5.0",
      "system": "Linux x86_64 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021"
    },
    "timestamp": "2021-10-07 23:00:01"
  },
  "version": "0x8030100"
}
```

**Additional context**
_Add any other context about the problem here._

**Comment by hacker-h** [comment]
Yes, just reproduced it with latest dev commit:
https://github.com/tasmota/decode-config/commit/ced97163474f0e13b697213a636a826b09623cb4
btw you might want to force push the commit message v9.2.0.9 => v9.5.0.9

**Comment by curzon01** [comment]
Issue cames up if the file '/tmp/tasmota01.local.dmp' does not exists, that's an OS issue, Why this sometimes happens on your system I don't know. I will catch the error and issue a meaningful message.

To prevent this, use the [obsolete parameter](https://github.com/tasmota/decode-config#obsolete-parameters) `--file` for files only because `-s` try to find out the source type automatically and if the file you give is reported as not existing from your OS this results in assuming it's an url.
